---
title: "scratch"
author: "JJayes"
date: "05/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

## Purpose

I need to create a number of tabs in an Rmarkdown document, depending on the contents of the data queried.

In short, the Rmarkdown document must have a tab for each factor in a dataset, and draw a ggplot in the tab.

I am using the fenced div structure to create tabsets from `xaringanExtra`.

```{r}
library(tidyverse)
library(xaringanExtra)
xaringanExtra::use_panelset()
df <- iris %>%
  as_tibble() %>%
  janitor::clean_names() %>%
  filter(species != "setosa")
```

```{r}
theme_set(theme_light())
```


```{r}
make_panel <- function(spec) {
  cat("\n")
  cat(".panel[.panel-name[", spec, "]\n")
  cat("Plot of", spec, "\n\n")
  p <- df %>%
    filter(species == spec) %>%
    ggplot(aes(sepal_length, sepal_width, colour = petal_width)) +
    geom_point()
  print(p)
  cat("\n")
  cat("]\n")
}
```


.panelset[

```{r, results='asis'}
species_tbl <- df %>% distinct(species)
for(i in species_tbl$species){
  
  make_panel(i)
  
}
```

]
